# This is a basic workflow to help you get started with Actions

name: Auto Update Database

# Controls when the action will run.
on:
  schedule:
    - cron: '30 21 * * *'
  push:
    branches: [master]
  #allows manual run
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v2
              with:
                python-version: '3.10.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax
                architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

            # Runs a single command using the runners shell
            # - name: Run a one-line script
            #   run: echo Hello, world!

            # Runs a set of commands using the runners shell
            # - name: Run a multi-line script
            #   run: |
            #     echo Add other actions to build,
            #     echo test, and deploy your project.
            - name: Install Dependencies
              run: |
                python -m pip install requests
                python -m pip install plotly
                python -m pip install pandas
                python -m pip install psutil
                python -m pip install kaleido

            - name: Update Database
              run: python makeDatabase.py

            - name: Parse Recent
              run: python parseRecentProbs.py

            - name: Update CFStats
              run: python getCFStats.py

            - name: Remove Temporary Files
              run : |
                rm diff.json

            - name: Git Configs
              run: |
                  git config --local user.email "ingyu1008@gmail.com"
                  git config --local user.name "BOT"

            - name: Git Commit
              run: |
                  git add .
                  git commit -m "AUTO : Update recent.json"

            - name: Git Push
              uses: ad-m/github-push-action@master
              with:
                  branch: "master"
                  github_token: $
