# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]
    pull_request:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Set up GCC
              uses: egor-tensin/setup-gcc@v1
              with:
                  platform: x64

            # Runs a single command using the runners shell
            # - name: Run a one-line script
            #   run: echo Hello, world!

            # Runs a set of commands using the runners shell
            # - name: Run a multi-line script
            #   run: |
            #     echo Add other actions to build,
            #     echo test, and deploy your project.
            - name: Compile Updater
              run: g++ -std=c++17 updateReadMe.cpp -o updateReadMe

            - name: Run Updater
              run: ./updateReadMe

            - name: Remove Compiled File
              run: rm updateReadMe

            - name: Git Configs
              run: |
                  git config --local user.email "ingyu1008@gmail.com"
                  git config --local user.name "BOT"

            - name: Git Commit
              run: |
                  git add .
                  git commit -m "AUTO : Update readme.md"

            - name: Git Push
              uses: ad-m/github-push-action@master
              with:
                  branch: "master"
                  github_token: $
